const mongoose = require('mongoose');

const tokenpageSchema = new mongoose.Schema({
  key: { type: String, required: true, unique: true }, // 'token'

  tokenHeroTopHeader: { type: String, default: "Stability Meets Scalability" },
  tokenHeroTitle: { type: String, default: "The Tokenomics Engine" },
  tokenHeroPrimaryBtnText: { type: String, default: "" },
  tokenHeroPrimaryBtnLink: { type: String, default: "" },
  tokenHeroSecondaryBtnText: { type: String, default: "" },
  tokenHeroSecondaryBtnLink: { type: String, default: "" },
  tokenHeroDescription: { type: String, default: "Explore how DINAAR and SAYA utility tokens drive transaction velocity, rewards, and staking pools." },

  tokenDualEcosystemTitle: { type: String, default: 'A Dual-Token Ecosystem' },
  tokenDualEcosystemDesc: { type: String, default: 'The IIC METAVERSE ecosystem is powered by two complementary digital assets, each designed to fulfill a distinct role within the platform:' },
  tokenDualEcosystemCard1Image: { type: String, default: '' },
  tokenDualEcosystemCard1Desc: { type: String, default: 'DINAAR - a gold-backed digital asset providing stability and real-world value' },
  tokenDualEcosystemCard2Image: { type: String, default: '' },
  tokenDualEcosystemCard2Desc: { type: String, default: 'SAYA - a utility-driven token enabling transactions, rewards & ecosystem participation' },
  tokenDualEcosystemBottomDesc: { type: String, default: 'Together, these tokens create a hybrid economic model that balances long-term value preservation with dynamic growth potential.' },

  tokenHybridBadge: { type: String, default: '[ WHY TWO TOKENS? ]' },
  tokenHybridTitle: { type: String, default: 'Hybrid Model' },
  tokenHybridDesc: { type: String, default: 'Traditional crypto models often face a trade-off between stability and growth. IIC METAVERSE solves this by separating these functions:' },
  tokenHybridCard1Icon: { type: String, default: '' },
  tokenHybridCard1Title: { type: String, default: 'DINAAR' },
  tokenHybridCard1Desc: { type: String, default: 'Stability & Value Preservation' },
  tokenHybridCard2Icon: { type: String, default: '' },
  tokenHybridCard2Title: { type: String, default: 'SAYA' },
  tokenHybridCard2Desc: { type: String, default: 'Utility & Ecosystem Growth' },
  tokenHybridBottomDesc: { type: String, default: 'This dual-token structure ensures that the ecosystem remains both resilient and scalable - capable of supporting real-world financial use cases while enabling innovation.' },

  tokenSystemTitle: { type: String, default: 'How the System Works' },
  tokenSystemDesc: { type: String, default: 'The IIC METAVERSE ecosystem follows a structured and compliant process that bridges traditional banking with blockchain-based assets.' },

  tokenSystemSlide1Badge: { type: String, default: '[ STEP - 1 ]' },
  tokenSystemSlide1Title: { type: String, default: 'Account Establishment' },
  tokenSystemSlide1DescList: { type: [String], default: [] },
  tokenSystemSlide1BtnText: { type: String, default: 'OPEN AN IICB ACCOUNT' },
  tokenSystemSlide1BtnLink: { type: String, default: '' },
  tokenSystemSlide1Image: { type: String, default: '' },

  tokenSystemSlide2Badge: { type: String, default: '[ STEP - 2 ]' },
  tokenSystemSlide2Title: { type: String, default: 'Fund Deposit' },
  tokenSystemSlide2DescList: { type: [String], default: [] },
  tokenSystemSlide2Image: { type: String, default: '' },

  tokenSystemSlide3Badge: { type: String, default: '[ STEP - 3 ]' },
  tokenSystemSlide3Title: { type: String, default: 'DINAAR Acquisition' },
  tokenSystemSlide3DescList: { type: [String], default: [] },
  tokenSystemSlide3Image: { type: String, default: '' },

  tokenSystemSlide4Badge: { type: String, default: '[ STEP - 4 ]' },
  tokenSystemSlide4Title: { type: String, default: 'Holding Period' },
  tokenSystemSlide4DescList: { type: [String], default: [] },
  tokenSystemSlide4FeatureHeading: { type: String, default: 'This structural holding framework supports:' },
  tokenSystemSlide4FeatureList: { type: [String], default: [] },
  tokenSystemSlide4Image: { type: String, default: '' },

  tokenSystemSlide5Badge: { type: String, default: '[ STEP - 5 ]' },
  tokenSystemSlide5Title: { type: String, default: 'Value Protection Mechanism' },
  tokenSystemSlide5DescList: { type: [String], default: [] },
  tokenSystemSlide5Heading: { type: String, default: 'Example:' },
  tokenSystemSlide5HeadingDescList: { type: [String], default: [] },
  tokenSystemSlide5Image: { type: String, default: '' },

  tokenSystemSlide6Badge: { type: String, default: '[ STEP - 6 ]' },
  tokenSystemSlide6Title: { type: String, default: 'Redemption & Exit' },
  tokenSystemSlide6DescList: { type: [String], default: [] },
  tokenSystemSlide6FeatureHeading: { type: String, default: 'All redemption requests are:' },
  tokenSystemSlide6FeatureList: { type: [String], default: [] },
  tokenSystemSlide6Image: { type: String, default: '' },

  tokenIntegrationSlide1Image: { type: String, default: '' },
  tokenIntegrationSlide1Title: { type: String, default: 'Institutional Integration' },
  tokenIntegrationSlide1DescList: { type: [String], default: [] },
  tokenIntegrationSlide1FeatureHeading: { type: String, default: 'International Investment Consortium Bank plays a key role in supporting the financial layer of the ecosystem by:' },
  tokenIntegrationSlide1Feature1Icon: { type: String, default: '' },
  tokenIntegrationSlide1Feature1Text: { type: String, default: 'Account management and onboarding' },
  tokenIntegrationSlide1Feature2Icon: { type: String, default: '' },
  tokenIntegrationSlide1Feature2Text: { type: String, default: 'Transaction verification and compliance' },
  tokenIntegrationSlide1Feature3Icon: { type: String, default: '' },
  tokenIntegrationSlide1Feature3Text: { type: String, default: 'Support for asset-backed financial flows' },

  tokenIntegrationSlide2Image: { type: String, default: '' },
  tokenIntegrationSlide2Title: { type: String, default: 'Economic Sustainability' },
  tokenIntegrationSlide2DescList: { type: [String], default: [] },
  tokenIntegrationSlide2Feature1Icon: { type: String, default: '' },
  tokenIntegrationSlide2Feature1Text: { type: String, default: 'Balanced token roles to avoid systemic instability' },
  tokenIntegrationSlide2Feature2Icon: { type: String, default: '' },
  tokenIntegrationSlide2Feature2Text: { type: String, default: 'Real-world asset backing to maintain trust' },
  tokenIntegrationSlide2Feature3Icon: { type: String, default: '' },
  tokenIntegrationSlide2Feature3Text: { type: String, default: 'Controlled token distribution mechanisms' },

  tokenIntegrationSlide3Image: { type: String, default: '' },
  tokenIntegrationSlide3Title: { type: String, default: 'Global Accessibility' },
  tokenIntegrationSlide3DescList: { type: [String], default: [] },
  tokenIntegrationSlide3Feature1Icon: { type: String, default: '' },
  tokenIntegrationSlide3Feature1Text: { type: String, default: 'Stable digital assets backed by gold' },
  tokenIntegrationSlide3Feature2Icon: { type: String, default: '' },
  tokenIntegrationSlide3Feature2Text: { type: String, default: 'Cross-border financial transactions' },
  tokenIntegrationSlide3Feature3Icon: { type: String, default: '' },
  tokenIntegrationSlide3Feature3Text: { type: String, default: 'Inclusive financial tools for global users' },

  tokenFutureTitle: { type: String, default: 'Step Into the Future' },
  tokenFutureDescList: { type: [String], default: [] },
  tokenFuturePrimaryBtnText: { type: String, default: 'JOIN THE ECOSYSTEM' },
  tokenFuturePrimaryBtnLink: { type: String, default: '' },
  tokenFutureSecondaryBtnText: { type: String, default: 'CONTACT US' },
  tokenFutureSecondaryBtnLink: { type: String, default: '' },
  tokenFutureTopRightImage: { type: String, default: '' },
  tokenFutureBottomLeftImage: { type: String, default: '' },

  tokenSmartCoinsTitle: { type: String, default: 'Smart Coins, Strong Value' },
  
  tokenSmartCoinsTab1BtnText: { type: String, default: 'Dinaar Coin' },
  tokenSmartCoinsTab1Title: { type: String, default: 'DINAAR - Gold-Backed Digital Asset' },
  tokenSmartCoinsTab1DescList: { type: [String], default: [] },
  tokenSmartCoinsTab1Image: { type: String, default: '' },
  tokenSmartCoinsTab1BgImage: { type: String, default: '' },
  tokenSmartCoinsTab1FeatureHeading: { type: String, default: 'Key Features' },
  tokenSmartCoinsTab1F1Title: { type: String, default: '' },
  tokenSmartCoinsTab1F1Desc: { type: String, default: '' },
  tokenSmartCoinsTab1F2Title: { type: String, default: '' },
  tokenSmartCoinsTab1F2Desc: { type: String, default: '' },
  tokenSmartCoinsTab1F3Title: { type: String, default: '' },
  tokenSmartCoinsTab1F3Desc: { type: String, default: '' },
  tokenSmartCoinsTab1F4Title: { type: String, default: '' },
  tokenSmartCoinsTab1F4Desc: { type: String, default: '' },
  tokenSmartCoinsTab1F5Title: { type: String, default: '' },
  tokenSmartCoinsTab1F5Desc: { type: String, default: '' },
  tokenSmartCoinsTab1ValueHeading: { type: String, default: 'Value Proposition' },
  tokenSmartCoinsTab1ValueDesc: { type: String, default: '' },

  tokenSmartCoinsTab2BtnText: { type: String, default: 'Saya Coin' },
  tokenSmartCoinsTab2Title: { type: String, default: 'SAYA - Utility & Growth Token' },
  tokenSmartCoinsTab2DescList: { type: [String], default: [] },
  tokenSmartCoinsTab2Image: { type: String, default: '' },
  tokenSmartCoinsTab2BgImage: { type: String, default: '' },
  tokenSmartCoinsTab2F1Heading: { type: String, default: 'Key Functions:' },
  tokenSmartCoinsTab2F1List: { type: [String], default: [] },
  tokenSmartCoinsTab2F2Heading: { type: String, default: 'Token Model Highlights:' },
  tokenSmartCoinsTab2F2List: { type: [String], default: [] },
  tokenSmartCoinsTab2ValueHeading: { type: String, default: 'Value Proposition' },
  tokenSmartCoinsTab2ValueDesc: { type: String, default: '' }

}, { timestamps: true });

module.exports = mongoose.model('TokenPage', tokenpageSchema);
